### ISSUE TITLE
Docker images for version 2.0 and 2.1 (from 13 March 2018) get stuck on "Starting to process block 000000009"

### ISSUE THREAD

**Issue by MatBje** [straumat/blockchain2graph#180]
# Prerequisites
Using the docker images for bitcoind, neo4j and tomcat with the war file for V2.0 and also V2.1 (from 13 March 2018) under Docker with CentOS 7 as the base OS.

Note!
There is an update with the same version number (2.1) that now does NOT use docker-compose but has other issues where Java reports a number of errors and heap dumps. I decided not to go with that version but instead with the binaries from 13 March 2018. Also because the structure using separate docker images is much cleaner and the process is not dependent on the bitcoind daemon that straumat has kindly provided.

# Expected Behavior
I would expect the blockchain to be fully imported into the Neo4j instance.

# Current Behavior
Currently the process seems ok except the message:
tomcat_1   | 20:34:46 - [03-18 20:34] No response from bitcoind for block n°000000009
tomcat_1   | 20:34:46 - ===================================
tomcat_1   | 20:34:46 - Starting to process block 000000009
tomcat_1   | 20:34:46 - [03-18 20:34] No response from bitcoind for block n°000000009
tomcat_1   | 20:34:46 - ===================================
tomcat_1   | 20:34:46 - Starting to process block 000000009
tomcat_1   | 20:34:46 - [03-18 20:34] No response from bitcoind for block n°000000009
tomcat_1   | 20:34:46 - ===================================
...
keeps appearing over and over and the system never finds a valid answer and no data is ever added to the Neo4J database.

# Steps to Reproduce
This is the process I have used  (well I did use the original docker-compose.yml file also with ther same result).

1. Install CentOS 7 with enough disk space free for the blockchain files and the Neo4J database.
Make sure the "/var/lib/docker" and "/opt" partitions or folders have at least 500 GB free.
Add the nano and wget commands by running:
yum -y install nano wget

2. Login as root and to ensure you do not store anything in the wrong place, move to the "/opt" folder or a suitable sub-folder:
cd /opt

3. Install Docker - If you don't have docker installed, run:
curl -sSL https://get.docker.com/ | sh

4. Install Docker-Compose by running:
sudo curl -L https://github.com/docker/compose/releases/download/1.20.0-rc2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

- Make the file executable.
chmod +x /usr/local/bin/docker-compose

- Verify that docker-compose is ok by running:
docker-compose --version

6. Start docker and make it autostart on boot by running:
systemctl start docker
systemctl enable docker

7. Check where docker will store its files by running:
docker info

You will most likely see:
"Docker Root Dir: /var/lib/docker"

Just make sure this folder has enough free space.

8. Open the firewall for the external ports needed by running:

- Ports for the web interface and Neo4J web access.
firewall-cmd --permanent --zone=public --add-port=8080/tcp
firewall-cmd --permanent --zone=public --add-port=7474/tcp

- These two ports are only needed to access the bitcoin daemon and the Neo4J Bolt interface.
firewall-cmd --permanent --zone=public --add-port=7687/tcp
firewall-cmd --permanent --zone=public --add-port=8332/tcp

- Reload i.e. activate the firewall rules.
firewall-cmd --reload
 
9. Add the "docker-compose.yml" file from the project (git repo) to the "/opt" folder (or your intended installation folder).

10. Update the docker-compose.yml file to look like this:
```
version: '2'
services:
  bitcoin:
    image: kylemanna/bitcoind
    ports:
      - 8332:8332
    volumes:
      - ./target/bitcoin/:/bitcoin/
    environment:
      - TXINDEX=1
      - RPCUSER=bitcoinrpc
      - RPCPASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - RPCTHREADS=4
      - REST=1
  neo4j:
    image: neo4j:3.3.3
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./target/neo4j/:/var/lib/neo4j/data/
    environment:
      - NEO4J_AUTH=neo4j/password
  tomcat:
    image: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./target/blockchain2graph.war:/usr/local/tomcat/webapps/blockchain2graph.war
    links:
      - bitcoin
      - neo4j
    environment:
      - BLOCKCHAIN2GRAPH_ADDRESS=localhost
      - BITCOIND_HOSTNAME=bitcoin
      - BITCOIND_USERNAME=bitcoinrpc
      - BITCOIND_PASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:password@neo4j:7687
```

This updated config will:
- Put the neo4j database in an external folder "./target/neo4j".
- Put the bitcoin database in an external folder "./target/bitcoin".
- Use the neo4j password "password" instead of "neo4j123".
- The option RPCTHREADS adds more threads to the bitcoind daemon to answer questions more quickly.
- The option TXINDEX=1 is VERY important to ensure the daemon provides all historic data and not just unspent transactions and your own data.

11. Add the blockchain2graph.war file to the folder named "/opt/target/".

12. The next command will download the blockchain and all necessary images. This will take a long time! Run:
docker-compose up -d

Note that version 0.16 of kylemanna/bitcoind crashes after approx 100 GB.
This seems to be a bug in the core application and a fix should hopefully be released quickly.

13. Try surfing to:
The blockchain2graph console at
http://<hostname>:8080/blockchain2graph/
and the neo4j console at
http://<hostname>:7474/browser/

The user name for Neo is "neo4j" (no quotes) and the password is "password".

- To see log output from the docker containers you can run this from the "/opt" folder:
docker-compose logs -f --tail="100"

- To connect a shell to any of the containers, run (type exit to return):
docker ps
docker exec -it <containerIdOrName> /bin/bash

- To improve the speed of the processing in Neo, you can create indexes by running these at the Neo console:
CREATE CONSTRAINT ON (n:BitcoinAddress) ASSERT n.address IS UNIQUE;
CREATE INDEX ON :BitcoinBlock(height);
CREATE CONSTRAINT ON (n:BitcoinTransaction) ASSERT n.txid IS UNIQUE;
CREATE INDEX ON :BitcoinTransactionOutput(txid, n);

**Comment by straumat** [comment]
Hi. Thanks for this detailed bug, I will investisgate but I have a question first. I added a cache  ( [https://github.com/straumat/blockchain2graph/blob/development/src/main/java/com/oakinvest/b2g/util/bitcoin/cache/BitcoinDataServiceCountCacheAspect.java](https://github.com/straumat/blockchain2graph/blob/development/src/main/java/com/oakinvest/b2g/util/bitcoin/cache/BitcoinDataServiceCountCacheAspect.java) ) that only check bitcoind count every 10 minutes. Did you wait 10 minutes ?

**Comment by MatBje** [comment]
Hi and many thanks for looking into this so quickly!!

Yes, in fact I waited for a full 24 hours in the hope that the issue was 
with the full blockchain not being present and the request potentially 
referring to a chain that had been placed "seriously" out of order with 
the required block not available until very late in the list of raw blocks.

To be fair, I have only wated for some 30 minutes with my latest trials, 
but as the issue is identical I assume the problem is elsewhere and 
possibly in the Bitcoin Core V0.16.0 release.

Best regards,

  Mats


p.s.
I hope you do not mind me asking, but will you go back to the original 
docker-compose packaging for V2.2? It was really neat i.m.h.o. as all 
services had their own separate containers.

**Comment by straumat** [comment]
In fact, if i deceided to make only one container, it's because i had similar issues to yours with OpenJDK (which is the default one with the provided neo4j container). If you have some time (one week), I can try to create again a docker-compose with separated neo4j and blockchain2graph and see if the bug is still here.

**Comment by MatBje** [comment]
Thanks!! Definitely worth waiting for :-)

Does block 000000009 refer to the raw block number?

If the requested block is not in blk00009.dat but in fact in one of the very last raw blocks it is possible that 24 hours was not enough to download all of the blockchain data for the bitcoind daemon. The complete number of blk files was 1211 on 16 March so it is possible that the problem will disappear if all blk files take more than 24 hours to download. My 24 hour test was thus not conclusive as I did not at the time know where to look for the blk files. Now that I do, I can verify that all files are indeed downloaded if the error remains. This will take some time too obviously.

Best,
 Mats

**Comment by straumat** [comment]
Yes, it's the block number 9.
You can make a try with my bitcoind server to see if the fully synced server works. 
But with my image here, i was able to load more thant 9 blocks in neo4j

**Comment by MatBje** [comment]
Very weird but interesting. When I tried the docker image referred to in the wiki for running docker I had a lot of java heapdumps show up. Thst's why I went back to the docker-compose version.

I'll try it again just in case.

Cheers! /Mats

**Comment by MatBje** [comment]
Just to confirm, I have 12 blocks in the blocks folder at the moment so the 9th is definitely downloaded by bitcoind.

[root@bitcoin01 ~]# ls /opt/target/bitcoin/.bitcoin/blocks/
blk00000.dat  blk00004.dat  blk00008.dat  blk00012.dat  rev00002.dat  rev00006.dat  rev00010.dat
blk00001.dat  blk00005.dat  blk00009.dat  index         rev00003.dat  rev00007.dat  rev00011.dat
blk00002.dat  blk00006.dat  blk00010.dat  rev00000.dat  rev00004.dat  rev00008.dat  rev00012.dat
blk00003.dat  blk00007.dat  blk00011.dat  rev00001.dat  rev00005.dat  rev00009.dat

**Comment by MatBje** [comment]
Is the wiki still correct i.e. to run:
`docker pull straumat/blockchain2graph:2.1-SNAPSHOT`
and then:
`docker run -ti -p 8080:8080 -p 7687:7687 -p 7474:7474 -v /opt/neo4j/:/var/lib/neo4j/data/ -e SYNC="true" straumat/blockchain2graph:2.1-SNAPSHOT`

**Comment by MatBje** [comment]
This is what I get when running the docker image:

```
[root@bitcoin01 opt]# docker run -ti -p 8080:8080 -p 7687:7687 -p 7474:7474 -v /opt/neo4j/:/var/lib/neo4j/data/ -e SYNC="true" straumat/blockchain2graph:2.1-SNAPSHOT
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /etc/neo4j
  logs:         /var/log/neo4j
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/run/neo4j
Starting Neo4j.
Started neo4j (pid 75). It is available at http://0.0.0.0:7474/
There may be a short delay until the server is ready.
See /var/log/neo4j/neo4j.log for current status.
=============================================================================================================
___.   .__                 __          .__           .__        ________                             .__
\_ |__ |  |   ____   ____ |  | __ ____ |  |__ _____  |__| ____  \_____  \   ________________  ______ |  |__
 | __ \|  |  /  _ \_/ ___\|  |/ // ___\|  |  \\__  \ |  |/    \  /  ____/  / ___\_  __ \__  \ \____ \|  |  \
 | \_\ \  |_(  <_> )  \___|    <\  \___|   Y  \/ __ \|  |   |  \/       \ / /_/  >  | \// __ \|  |_> >   Y  \
 |___  /____/\____/ \___  >__|_ \\___  >___|  (____  /__|___|  /\_______ \\___  /|__|  (____  /   __/|___|  /
     \/                 \/     \/    \/     \/     \/        \/         \/_____/            \/|__|        \/

=============================================================================================================
21:26:00 - Starting Application v2.1-SNAPSHOT on 850fd54135db with PID 119 (/app.jar started by root in /)
21:26:00 - No active profile set, falling back to default profiles: default
21:26:09 - Constraints and indexes creation
21:26:09 - Driver instance org.neo4j.driver.internal.InternalDriver@378542de created
21:26:10 - Closing connection pool towards localhost:7687
21:26:12 - Error creating constraints & indexes : Could not create driver instance
org.neo4j.ogm.exception.ConnectionException: Could not create driver instance
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.initializeDriver(BoltDriver.java:124)
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.checkDriverInitialized(BoltDriver.java:103)
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.newTransaction(BoltDriver.java:91)
        at org.neo4j.ogm.session.transaction.DefaultTransactionManager.openTransaction(DefaultTransactionManager.java:68)
        at org.neo4j.ogm.session.Neo4jSession.beginTransaction(Neo4jSession.java:489)
        at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:542)
        at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:523)
        at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.query(ExecuteQueriesDelegate.java:102)
        at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.query(ExecuteQueriesDelegate.java:82)
        at org.neo4j.ogm.session.Neo4jSession.query(Neo4jSession.java:419)
        at com.oakinvest.b2g.configuration.Neo4jConfiguration.createConstraintsAndIndexes(Neo4jConfiguration.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:369)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:312)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
        at com.oakinvest.b2g.Application.main(Application.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Unable to connect to localhost:7687, ensure the database is running and that there is a working network connection to it.
        at org.neo4j.driver.internal.async.ChannelConnectedListener.databaseUnavailableError(ChannelConnectedListener.java:84)
        at org.neo4j.driver.internal.async.ChannelConnectedListener.operationComplete(ChannelConnectedListener.java:78)
        at org.neo4j.driver.internal.async.ChannelConnectedListener.operationComplete(ChannelConnectedListener.java:37)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7687
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        ... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted
21:26:15 - Driver instance org.neo4j.driver.internal.InternalDriver@4ee2a7f3 created
21:26:15 - Closing connection pool towards localhost:7687
21:26:15 - Started Application in 16.632 seconds (JVM running for 17.956)
21:26:18 - Unexpected error occurred in scheduled task.
org.springframework.transaction.CannotCreateTransactionException: Could not open Neo4j Session for transaction; nested exception is org.neo4j.ogm.exception.ConnectionException: Could not create driver instance
        at org.springframework.data.neo4j.transaction.Neo4jTransactionManager.doBegin(Neo4jTransactionManager.java:214)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:474)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at com.oakinvest.b2g.batch.bitcoin.BitcoinBatch$$EnhancerBySpringCGLIB$$fcf6b53e.execute(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.ogm.exception.ConnectionException: Could not create driver instance
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.initializeDriver(BoltDriver.java:124)
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.checkDriverInitialized(BoltDriver.java:103)
        at org.neo4j.ogm.drivers.bolt.driver.BoltDriver.newTransaction(BoltDriver.java:91)
        at org.neo4j.ogm.session.transaction.DefaultTransactionManager.openTransaction(DefaultTransactionManager.java:68)
        at org.neo4j.ogm.session.Neo4jSession.beginTransaction(Neo4jSession.java:494)
        at org.springframework.data.neo4j.transaction.Neo4jTransactionManager.doBegin(Neo4jTransactionManager.java:192)
        ... 20 common frames omitted
Caused by: org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Unable to connect to localhost:7687, ensure the database is running and that there is a working network connection to it.
        at org.neo4j.driver.internal.async.ChannelConnectedListener.databaseUnavailableError(ChannelConnectedListener.java:84)
        at org.neo4j.driver.internal.async.ChannelConnectedListener.operationComplete(ChannelConnectedListener.java:78)
        at org.neo4j.driver.internal.async.ChannelConnectedListener.operationComplete(ChannelConnectedListener.java:37)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 common frames omitted
Caused by: org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7687
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        ... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted
21:26:18 - Driver instance org.neo4j.driver.internal.InternalDriver@7fd160a9 created
21:26:18 - Closing connection pool towards localhost:7687
21:26:20 - Unexpected error occurred in scheduled task.
```

**Comment by straumat** [comment]
Please, try again removing "-v /opt/neo4j/:/var/lib/neo4j/data/ " as there are some issues with files being created for root. I'm fiwing it right now.

**Comment by MatBje** [comment]
Brilliant!!! Now data is being added to Neo and no errors!

**Comment by straumat** [comment]
Ok. I try to quickly fix the ability to map to a local direrctory with the Docker image.
And by the end of the week. I try to make a docker-compose with three different containers (bitcoind, neo4j, blockchain2graph).

**Comment by MatBje** [comment]
Excellent!! Many thanks indeed!!

![image](https://user-images.githubusercontent.com/16295393/37571196-bedbed8c-2af9-11e8-9077-06d71a74bb7f.png)

**Comment by straumat** [comment]
Hello
I have created a much more simple image with only blockchain2graph : https://github.com/straumat/blockchain2graph/blob/development/Dockerfile

and i've also added a docker-compose that uses neo4j container. It uses my public bitcoind server but you can add your server in the configuration or add a bitcoind container : https://github.com/straumat/blockchain2graph/blob/development/docker-compose.yml


https://github.com/straumat/blockchain2graph/commit/af5401b9701d50e03c5947a210b4371b4b3b057f

**Comment by MatBje** [comment]
Brilliant!! Many thanks!!

I'll give it a go later today. Seems a very neat way of packaging and great that you found a way to fix the Neo folder output as well as the elusive Block 000000009 issue.

I'll add some more feed back once I have tested the new setup.

I will probably try adding the Bitcoin Core image to the docker compose configuration the way you initially set this up, just to ensure I get a "self-contained" system.

Cheers!
/Mats

**Comment by MatBje** [comment]
Hi again,

It seems the issue with the Bitcoin Core daemon is still there when I try to access it from my own machine rather than use the one on your server.
The program gets stuck when trying to access block 000000009 i.e. gets no response from bitcoind.

Are you using the same bitcoind service on your server that you used in the original docker-compose file? I.e. this configuration:

```
 bitcoin:
    image: kylemanna/bitcoind
    ports:
      - 8332:8332
    volumes:
      - ./target/bitcoin/:/bitcoin/
    environment:
      - TXINDEX=1
      - RPCUSER=bitcoinrpc
      - RPCPASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - RPCTHREADS=4
      - REST=1
```

or are you running an older version like 0.15.0 ?

It seems bitcoind does not download new blocks. My block cache/index holds only block blk00000.dat and no new data seems to be added despite the requests for block 9 from the blockchain2 neo process.

Any thoughts on what might be wrong?

Best,
  /Mats

p.s.
[docker-compose.yml.txt](https://github.com/straumat/blockchain2graph/files/1825839/docker-compose.yml.txt)


I have attached the complete docker-compose.yml file I am trying this with.

**Comment by MatBje** [comment]
I seem to have solved it. Not absolutely sure which parameter did it but possibly the **rpcallowip** setting. The new docker-compose.yml file now has this content:

```
version: '2'
services:
  bitcoin:
    image: kylemanna/bitcoind:latest
    ports:
      - 127.0.0.1:8332:8332
      - 8333:8333
    volumes:
      - ./target/bitcoin:/bitcoin
    environment:
      - TXINDEX=1
      - RPCUSER=bitcoinrpc
      - RPCPASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - RPCTHREADS=4
      - REST=1
      - SERVER=1
      - RPCALLOWIP=0.0.0.0/0
      - REGTEST=1
  neo4j:
    image: neo4j:3.3.3
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./target/neo4j/:/var/lib/neo4j/data/
    environment:
      - NEO4J_AUTH=neo4j/password
  blockchain2graph:
    image: straumat/blockchain2graph:2.1-SNAPSHOT
    ports:
      - 8080:8080
    links:
      - bitcoin
      - neo4j
    environment:
      - BLOCKCHAIN2GRAPH_ADDRESS=localhost
      - BITCOIND_HOSTNAME=bitcoin
      - BITCOIND_USERNAME=bitcoinrpc
      - BITCOIND_PASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:password@neo4j:7687
```

**Comment by MatBje** [comment]
Not sure yet. It did work and read blocks up to 000000127 and then I stopped the process to try to verify what made it work. But now that I restart I keep getting stuck on block 000000009 again. Weird...

I am worried the bitcoind has some quirk I do not understand properly. I'll let it run for a couple of hours to see if I get enough blocks to get past block 000000009 again.

**Comment by MatBje** [comment]
Hi again Stéphane,

I am still stuck. But the issue seems to be with bitcoind and not your code so I guess I have to dig deeper into bitcoind to understand why it seems so slow to download new blocks, if indeed any new blocks are being downloaded at all. There is a lot of log output but it seems no new block files appear in the .bitcoin/blocks folder or else each block takes an inordinate amount of time.

I read it could be due to the verification process of each block and I am using standard spinning disks on this old server so maybe this is why. But on the other hand, for a little while it all seemed to work just as well as when I accessed the blockchain from your server. Why this worked I fail to understand. I am so far unable to reproduce it and remain stuck on block 00000009.

Best,
  /Mats

**Comment by straumat** [comment]
Hi.

My public bitcoind server is not a docker image, it's a compiled release of bitcoind 0.15.1 ( https://bitnodes.earn.com/nodes/5.196.65.205-8333/ ).

If i add the bitcoind image like yours. I also get stuck on block9.

So it really seems to be a problem with bitcoind container.

**Comment by MatBje** [comment]
Many thanks Stéphane!!

Then I know I am not fighting windmills :)  I'll try to find a better solution.

Let's consider the original issue fixed then and I'll just try to find a better Bitcoin Core daemon to rely on.

Once again many warm thanks for writing this cool peace of code and for allowing us/me to experiment with representing the blockchain in Neo4J. I have learnt a lot about the blockchain and docker in the last few days.

Best regards,
  Mats

**Comment by straumat** [comment]
Hi ! I found a solution with another bitcoind container : https://github.com/straumat/blockchain2graph/blob/72d25daed00eabda6aa5e9673ab63212d6e16bb8/docker-compose.yml It should work well.

**Comment by MatBje** [comment]
Wow! You are the best! Works beautifully!!
Cheers! /Mats
